language: node_js
node_js:
- 8

script:
- CI=true npm run build

deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    tags: true

before_deploy:
- openssl aes-256-cbc -K $encrypted_033bf435fd29_key -iv $encrypted_033bf435fd29_iv -in .travis/blasteroids.enc -out .travis/blasteroids -d
- ssh-add .travis/blasteroids
- git remote set-url origin git@github.com:howech/blasteroids.git
- git config --global user.email "Travis<chris+travis@howeville.com>"
- git config --global user.name "howech (via travis)"
