language: node_js
node_js:
- 8
script:
- CI=true npm run build
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    tags: true
before_deploy:
- ssh-add blasteroids
- git remote set-url origin https://${GH_TOKEN}/github.com/howech/blasteroids.git
- git config --global user.email "Travis<chris+travis@howeville.com>"
- git config --global user.name "howech (via travis)"

repos:
  howech/blasteroids:
    endpoint: https://api.travis-ci.com/
